name = "bucket"
version = "1.3.0"
description = "Gleam S3 API client, suitable for AWS S3, Garage, Minio, Storj, Backblaze B2, Cloudflare R2, Ceph, Wasabi, and so on!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "bucket" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"
aws4_request = ">= 1.0.0 and < 2.0.0"
xmlm = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 5.0.0"
xmb = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
